"use client";

import { useState, useEffect } from "react";
import { GlowCard } from "@/components/ui/GlowCard";
import { RiskGauge } from "@/components/ui/RiskGauge";
import { Button } from "@/components/ui/Button";
import { ShieldAlert, AlertTriangle, CheckCircle, Info, Download, HeartPulse, BrainCircuit, Droplet, ListChecks, RefreshCw } from "lucide-react";
import { motion } from "framer-motion";
import { api } from "@/lib/api";

interface Risk {
    label: string;
    percentage: number;
    level: string;
}

interface Recommendation {
    title: string;
    desc: string;
    type: "alert" | "warning" | "success" | string;
}

export default function InsightsPage() {
    const [loading, setLoading] = useState(true);
    const [data, setData] = useState<{ risks: Risk[], recommendations: Recommendation[] } | null>(null);

    const fetchInsights = async () => {
        setLoading(true);
        try {
            const res = await api.get("/insights/analysis");
            setData(res.data);
        } catch (error) {
            console.error("Failed to fetch insights", error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchInsights();
    }, []);

    const getIcon = (type: string) => {
        switch (type) {
            case "alert": return AlertTriangle;
            case "success": return CheckCircle;
            default: return Info;
        }
    };

    const getColorClasses = (type: string) => {
        switch (type) {
            case "alert": return { text: "text-accent-danger", bg: "bg-accent-danger/10", border: "border-accent-danger/20" };
            case "success": return { text: "text-accent-secondary", bg: "bg-accent-secondary/10", border: "border-accent-secondary/20" };
            case "warning": return { text: "text-accent-warm", bg: "bg-accent-warm/10", border: "border-accent-warm/20" };
            default: return { text: "text-accent-primary", bg: "bg-accent-primary/10", border: "border-accent-primary/20" };
        }
    };

    const handleExport = () => {
        if (!data) return;
        const report = `NUTRISYNC AI : HEALTH INSIGHTS REPORT\n` +
            `==================================\n\n` +
            `RISK ASSESSMENT:\n` +
            data.risks.map(r => `- ${r.label}: ${r.percentage}% (${r.level})`).join('\n') +
            `\n\nRECOMMENDATIONS:\n` +
            data.recommendations.map(re => `- [${re.title}] ${re.desc}`).join('\n') +
            `\n\n-- End of Neural Protocol --`;

        const blob = new Blob([report], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `NutriSync_Insights_${new Date().toISOString().split('T')[0]}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-8 pb-10">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 border-b border-border-glow/30 pb-6">
                <div>
                    <h1 className="text-3xl font-display font-bold flex items-center gap-3">
                        <ShieldAlert className="w-8 h-8 text-accent-danger drop-shadow-[0_0_8px_rgba(255,23,68,0.5)]" />
                        AI Health Insights
                    </h1>
                    <p className="text-sm text-muted mt-2 max-w-lg">
                        Prescriptive intelligence generated by the Gemini Neural Engine and your persistent bio-profile.
                    </p>
                </div>

                <div className="flex gap-4">
                    <Button variant="secondary" onClick={fetchInsights} disabled={loading} className="gap-2">
                        <RefreshCw className={loading ? "animate-spin" : ""} /> Recalibrate
                    </Button>
                    <Button variant="secondary" onClick={handleExport} disabled={!data} className="gap-2 hidden sm:flex">
                        <Download className="w-4 h-4" /> Export Protocol
                    </Button>
                </div>
            </div>

            {loading ? (
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 animate-pulse">
                    <div className="lg:col-span-8 h-96 bg-surface rounded-2xl border border-border-glow/20" />
                    <div className="lg:col-span-4 h-96 bg-surface rounded-2xl border border-border-glow/20" />
                </div>
            ) : (
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                    {/* Risk Gauges - 8 cols */}
                    <div className="lg:col-span-8 space-y-8">
                        <GlowCard className="p-6">
                            <h2 className="text-lg font-display font-bold flex items-center gap-2 mb-6 border-b border-border-glow/30 pb-3">
                                <HeartPulse className="w-5 h-5 text-accent-warm" /> Clinical Projections
                            </h2>

                            <div className="flex flex-wrap justify-around items-center gap-6">
                                {data?.risks.map((risk, i) => (
                                    <div key={i} className="flex flex-col items-center">
                                        <RiskGauge label={risk.label} percentage={risk.percentage} riskLevel={risk.level as "Low" | "Moderate" | "High"} />
                                    </div>
                                ))}
                            </div>

                            <div className="mt-6 p-4 rounded-xl bg-surface/50 border border-border-glow/20 text-sm text-primary/80 flex gap-3">
                                <Info className="w-5 h-5 text-accent-primary shrink-0 mt-0.5" />
                                <p>
                                    Projections are based on your persistent bio-data. Higher percentages indicate a need for protocol review with your healthcare provider.
                                </p>
                            </div>
                        </GlowCard>

                        <GlowCard className="p-6" glow>
                            <h2 className="text-lg font-display font-bold flex items-center gap-2 mb-6 border-b border-border-glow/30 pb-3">
                                <BrainCircuit className="w-5 h-5 text-accent-primary" /> AI Smart Recommendations
                            </h2>

                            <div className="space-y-4">
                                {data?.recommendations.map((rec, i) => {
                                    const Icon = getIcon(rec.type);
                                    const colors = getColorClasses(rec.type);
                                    return (
                                        <motion.div
                                            key={i}
                                            initial={{ opacity: 0, x: -20 }}
                                            animate={{ opacity: 1, x: 0 }}
                                            transition={{ delay: i * 0.1 }}
                                            className={`p-4 rounded-xl bg-surface border ${colors.border} flex items-start gap-4 transition-transform hover:scale-[1.01]`}
                                        >
                                            <div className={`p-2 rounded-lg ${colors.bg} ${colors.text} shrink-0`}>
                                                <Icon className="w-5 h-5" />
                                            </div>
                                            <div>
                                                <h4 className="font-display font-bold text-primary mb-1">{rec.title}</h4>
                                                <p className="text-sm text-muted">{rec.desc}</p>
                                            </div>
                                        </motion.div>
                                    );
                                })}
                            </div>
                        </GlowCard>
                    </div>

                    {/* Nutritional Status & Grocery List - 4 cols */}
                    <div className="lg:col-span-4 space-y-8">
                        <GlowCard className="p-6">
                            <h2 className="text-lg font-display font-bold flex items-center gap-2 mb-4 border-b border-border-glow/30 pb-3">
                                <Droplet className="w-5 h-5 text-accent-primary" /> Micro-Status
                            </h2>

                            <div className="space-y-4">
                                <div className="flex items-center justify-between">
                                    <span className="text-sm font-medium">Iron</span>
                                    <span className="text-xs font-mono uppercase px-2 py-1 rounded-sm border border-accent-danger bg-accent-danger/10 text-accent-danger">Deficient 🔴</span>
                                </div>
                                <div className="flex items-center justify-between">
                                    <span className="text-sm font-medium">B12</span>
                                    <span className="text-xs font-mono uppercase px-2 py-1 rounded-sm border border-accent-warm bg-accent-warm/10 text-accent-warm">Below Target 🟡</span>
                                </div>
                                <div className="flex items-center justify-between">
                                    <span className="text-sm font-medium">D3</span>
                                    <span className="text-xs font-mono uppercase px-2 py-1 rounded-sm border border-accent-secondary bg-accent-secondary/10 text-accent-secondary">Optimal 🟢</span>
                                </div>
                            </div>
                        </GlowCard>

                        <GlowCard className="p-6 relative overflow-hidden h-full min-h-[300px]">
                            <div className="absolute top-0 right-0 w-32 h-32 bg-accent-secondary/5 blur-[40px] rounded-full pointer-events-none" />

                            <h2 className="text-lg font-display font-bold flex items-center gap-2 mb-4 border-b border-border-glow/30 pb-3">
                                <ListChecks className="w-5 h-5 text-accent-secondary" /> Grocery Manifest
                            </h2>
                            <p className="text-xs text-muted mb-4 font-mono">Synced from AI Protocol.</p>

                            <div className="space-y-5 text-sm">
                                <div>
                                    <ul className="space-y-2">
                                        <li className="flex items-center gap-2 text-primary/80"><div className="w-3 h-3 rounded-full border border-border-glow bg-surface" /> Lean Protein Sources</li>
                                        <li className="flex items-center gap-2 text-primary/80"><div className="w-3 h-3 rounded-full border border-border-glow bg-surface" /> Leafy Greens</li>
                                        <li className="flex items-center gap-2 text-primary/80"><div className="w-3 h-3 rounded-full border border-border-glow bg-surface" /> Complex Carbohydrates</li>
                                    </ul>
                                </div>
                            </div>

                            <div className="mt-8 pt-4 border-t border-border-glow/20">
                                <Button className="w-full text-sm h-10 gap-2 font-mono uppercase tracking-wider">
                                    Sync to Devices
                                </Button>
                            </div>
                        </GlowCard>
                    </div>
                </div>
            )}
        </div>
    );
}
